// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yffznweqrdkoibzygvpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZnpud2VxcmRrb2lienlndnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjEwMTUsImV4cCI6MjA2NjgzNzAxNX0.fRYCU7l90A1rQ7thShBvPc4s1FpP13L5fBDg0Ie1yzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});